export const IssueActionTypes = {
	SET_ISSUE_ID: 'SET_ISSUE_ID',
	TOGGLE_CREATE_ISSUE_MODAL: 'TOGGLE_CREATE_ISSUE_MODAL',
	TOGGLE_DELETE_ISSUE_MODAL: 'TOGGLE_DELETE_ISSUE_MODAL',
	TOGGLE_EDIT_ISSUE_MODAL: 'TOGGLE_EDIT_ISSUE_MODAL',
	TOGGLE_DELETE_ISSUES: 'TOGGLE_DELETE_ISSUES',
	TOGGLE_EDIT_ISSUES: 'TOGGLE_EDIT_ISSUES',
	SET_ISSUES_ARRAY: 'SET_ISSUES_ARRAY',
	ClOSE_SORT_OPTIONS_BOX: 'CLOSE_SORT_OPTIONS_BOX',
	CLOSE_LABEL_OPTIONS_BOX: 'CLOSE_LABEL_OPTIONS_BOX',
	CLOSE_STATUS_OPTIONS_BOX: 'CLOSE_STATUS_OPTIONS_BOX',
	TOGGLE_SORT_OPTIONS_BOX: 'TOGGLE_SORT_OPTIONS_BOX',
	TOGGLE_LABEL_OPTIONS_BOX: 'TOGGLE_LABEL_OPTIONS_BOX',
	TOGGLE_STATUS_OPTIONS_BOX: 'TOGGLE_STATUS_OPTIONS_BOX',
	EMPTY_ISSUES_ARRAY: 'EMPTY_ISSUES_ARRAY',
	SET_SEARCH_TEXT: 'SET_SEARCH_TEXT'
};
