export const IssueActionTypes = {
	TOGGLE_CREATE_ISSUE_MODAL: 'TOGGLE_CREATE_ISSUE_MODAL',
	TOGGLE_DELETE_ISSUE_MODAL: 'TOGGLE_DELETE_ISSUE_MODAL',
	TOGGLE_EDIT_ISSUE_MODAL: 'TOGGLE_EDIT_ISSUE_MODAL',
	SET_ISSUES_ARRAY: 'SET_ISSUES_ARRAY',
	EMPTY_ISSUES_ARRAY: 'EMPTY_ISSUES_ARRAY'
};
