export const projectActionTypes = {
	TOGGLE_CREATE_PROJECT_MODAL: 'TOGGLE_CREATE_PROJECT_MODAL',
	SET_PROJECTS_ARRAY: 'SET_PROJECTS_ARRAY',
	SET_PROJECT_ID: 'SET_PROJECT_ID',
	TOGGLE_DELETE_PROJECTS: 'TOGGLE_DELETE_PROJECTS',
	TOGGLE_EDIT_PROJECTS: 'TOGGLE_EDIT_PROJECTS',
	TOGGLE_DELETE_PROJECT_MODAL: 'TOGGLE_DELETE_PROJECT_MODAL',
	TOGGLE_EDIT_PROJECT_MODAL: 'TOGGLE_EDIT_PROJECT_MODAL'
};
