export const sideBarActionTypes = {
	ADD_SIDEBAR_ITEM_VISIBILITY: 'ADD_SIDEBAR_ITEM_VISIBILTY',
	TOGGLE_PROJECTS_SUBCATEGORY: 'TOGGLE_PROJECTS_SUBCATEGORY',
	TOGGLE_TOOLS_SUBCATEGORY: 'TOGGLE_TOOLS_SUBCATEGORY',
	TOGGLE_SIDEBAR_ITEM_VISIBILITY: 'TOGGLE_SIDEBAR_ITEM_VISIBILITY'
};
