export const userActionTypes = {
	SET_USER_ID: 'SET_USER_ID',
	SET_ROLES: 'SET_ROLES',
	ADD_ROLES: 'ADD_ROLES',
	SET_USER_NAME: 'SET_USER_NAME',
	SET_COMMENT_CREATOR: 'SET_COMMENT_CREATOR',
	SET_ISSUE_CREATOR: 'SET_ISSUE_CREATOR',
	SET_TEAM_MANAGER: 'SET_TEAM_MANAGER',
	SET_PROJECT_MANAGER: 'SET_PROJECT_MANAGER',
	TOGGLE_APP_THEME: 'TOGGLE_APP_THEME',
	SIGN_IN: 'SIGN_IN',
	SIGN_OUT: 'SIGN_OUT'
};
