version: "3"
services:
   redis: 
      image: 'redis:latest'
   api:
      build: 
         dockerfile: Dockerfile.dev
         context: ./
      volumes:
       - /app/node_modules
       - ./:/app
      environment: 
       - REDIS_HOST=redis
       - REDIS_PORT=6379
      ports:
       - "4001:80"