export const userActionTypes = {
	SET_USER_ID: 'SET_USER_ID',
	SET_IS_ADMIN: 'SET_IS_ADMIN',
	SET_USER_NAME: 'SET_USER_NAME',
	TOGGLE_APP_THEME: 'TOGGLE_APP_THEME',
	SIGN_IN: 'SIGN_IN',
	SIGN_OUT: 'SIGN_OUT'
};
