export enum sideBarActionTypes {
	TOGGLE_SIDEBAR,
	TOGGLE_SIDEBAR_IS_CLOSING,
	TOGGLE_SIDEBAR_IS_OPENING,
	ADD_SIDEBAR_ITEM_VISIBILITY,
	TOGGLE_PROJECTS_SUBCATEGORY,
	TOGGLE_TOOLS_SUBCATEGORY,
	TOGGLE_SIDEBAR_ITEM_VISIBILITY
}
