export const teamActionTypes = {
	SET_TEAM_ID: 'SET_TEAM_ID',
	SET_TEAMS_ARRAY: 'SET_TEAMS_ARRAY',
	SWITCH_TEAMS: 'SWITCH_TEAMS',
	TOGGLE_DELETE_TEAMS: 'TOGGLE_DELETE_TEAMS',
	TOGGLE_EDIT_TEAMS: 'TOGGLE_EDIT_TEAMS',
	TOGGLE_DELETE_TEAM_MODAL: 'TOGGLE_DELETE_TEAM_MODAL',
	TOGGLE_EDIT_TEAM_MODAL: 'TOGGLE_EDIT_TEAM_MODAL',
	TOGGLE_CREATE_TEAM_MODAL: 'TOGGLE_CREATE_TEAM_MODAL'
};
