export const messageActionTypes = {
	TOGGLE_SHOULD_RENDER_MESSAGE: 'TOGGLE_SHOULD_RENDER_MESSAGE',
	TOGGLE_IS_OPENING_MESSAGE: 'TOGGLE_IS_OPENING_MESSAGE',
	TOGGLE_IS_CLOSING_MESSAGE: 'TOGGLE_IS_CLOSING_MESSAGE',
	SET_MESSAGE_TEXT: 'SET_MESSAGE_TEXT',
	TOGGLE_NOTIFICATION_MODAL: 'TOGGLE_NOTIFICATION_MODAL'
};
